active: dev
domain: qjfu.cn
scheme: http
port: 8080

swagger:
  port: 9090

# 存储方案二选一， mysql or sqlite
storage-driver: mysql
mysql:
  master:
    user: root
    password: mysql123
    host: 127.0.0.1
    port: 3306
    database: study_notes
    charset: utf8mb4
    timezone: Asia/Shanghai
sqlite:
  master:
    storage-file: sqlite3.db
    timezone: Asia/Shanghai
redis:
  master:
    host: 127.0.0.1
    port: 6379
    password:
    db: 0
# 二维码信息设置
qrcode:
  width: 200
  height: 200
  buffer: 4096
  url: https://demo.com?id=%s