# 环境 dev / test / product
active: dev

# 时区
timezone: Asia/Shanghai

# 域名端口方式，可单独提供服务
domain: localhost
scheme: http
port: 8080

# socket 方式，结合nginx转发
sock: /tmp/studynote.sock

# swagger wiki 服务端口
swagger:
  port: 9090

mysql:
  master:
    user: root
    password: mysql123
    host: 127.0.0.1
    port: 3306
    database: yupengsir_prod
    charset: utf8mb4

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0

# es配置
es:
  - http://localhost:9200