# 环境 dev / test / uat / pre / product
active: dev

# 时区
timezone: Asia/Shanghai

# 域名端口方式，可单独提供服务
domain: localhost
scheme: http
port: 8090

# socket 方式，结合nginx转发
sock: /tmp/studynotes.sock

# swagger wiki 服务端口
swagger:
  port: 9099

mysql:
  master:
    user: root
    password: mysql123
    host: 127.0.0.1
    port: 3306
    database: study_notes
    charset: utf8mb4

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0

# es配置
es:
  - http://localhost:9200

# minio
minio:
  endpoint: "127.0.0.1:9000"
  access_key_id: "testtest"
  secret_access_key: "testtest"
  use_ssl: false