apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
  namespace: default
  labels:
    app: blog-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
    spec:
      containers:
      - name: blog-backend
        image: docker.io/itsos/blog-backend:v1.0.11
        ports:
        - containerPort: 8090
        volumeMounts:
            - name: config-volume
              mountPath: /data/config
              readOnly: true
      volumes:
      - name: config-volume
        configMap:
            name: blog-backend-config

# kubectl create configmap blog-backend-config --from-file=./config/config.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog-backend
  name: blog-backend
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8090
  selector:
    app: blog-backend
  type: ClusterIP
