apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
  namespace: default
  labels:
    app: blog-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      containers:
      - name: blog-frontend
        image: docker.io/itsos/blog-frontend:v1.0.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog-frontend
  name: blog-frontend
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blog-frontend
  type: ClusterIP
