// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/article/content": {
            "get": {
                "description": "文章内容详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客前台接口"
                ],
                "summary": "文章内容详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文章标题",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "详情数据",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vo.ArticleContentVO"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/article/list": {
            "get": {
                "description": "分页接口通过page递增获取更多",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客前台接口"
                ],
                "summary": "首页文章列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页条数",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "列表数据",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vo.ArticleVO"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/article/rank": {
            "get": {
                "description": "根据访问量排序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客前台接口"
                ],
                "summary": "文章访问TOP50",
                "responses": {
                    "200": {
                        "description": "列表数据",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vo.ArticleAccessTimesVO"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "datamodels.Article": {
            "type": "object",
            "properties": {
                "ctime": {
                    "type": "string",
                    "readOnly": true
                },
                "id": {
                    "description": "文章表ID",
                    "type": "integer",
                    "readOnly": true,
                    "example": 1
                },
                "intro": {
                    "description": "简介",
                    "type": "string"
                },
                "is_del": {
                    "description": "0未删除；1已删除",
                    "type": "integer"
                },
                "is_state": {
                    "description": "状态1私密；2公开",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "uid": {
                    "description": "编辑者id",
                    "type": "integer"
                },
                "utime": {
                    "type": "string",
                    "readOnly": true
                }
            }
        },
        "datamodels.ArticleContent": {
            "type": "object",
            "properties": {
                "aid": {
                    "description": "文章id",
                    "type": "integer"
                },
                "data": {
                    "description": "文章内容",
                    "type": "string"
                }
            }
        },
        "errors.Errors": {
            "type": "object",
            "properties": {
                "errCode": {
                    "type": "integer",
                    "example": 4000000
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "vo.ArticleAccessTimesVO": {
            "type": "object",
            "properties": {
                "access_times": {
                    "description": "访问次数",
                    "type": "integer"
                },
                "title": {
                    "description": "文章标题",
                    "type": "string"
                }
            }
        },
        "vo.ArticleContentVO": {
            "type": "object",
            "properties": {
                "article": {
                    "description": "文章信息",
                    "$ref": "#/definitions/vo.ArticleVO"
                },
                "articleContent": {
                    "description": "文章内容",
                    "$ref": "#/definitions/datamodels.ArticleContent"
                },
                "navigation": {
                    "description": "导航",
                    "$ref": "#/definitions/vo.NavigationVO"
                },
                "tags": {
                    "description": "标签文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.TagVO"
                    }
                },
                "topics": {
                    "description": "专题文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.TopicVO"
                    }
                }
            }
        },
        "vo.ArticleVO": {
            "type": "object",
            "properties": {
                "article": {
                    "$ref": "#/definitions/datamodels.Article"
                },
                "duration": {
                    "description": "持续时间",
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.NavigationVO": {
            "type": "object",
            "properties": {
                "nextTitle": {
                    "description": "下一文章title",
                    "type": "string"
                },
                "prevTitle": {
                    "description": "上一文章title",
                    "type": "string"
                }
            }
        },
        "vo.TagVO": {
            "type": "object",
            "properties": {
                "article": {
                    "description": "文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.ArticleAccessTimesVO"
                    }
                },
                "title": {
                    "description": "专题名",
                    "type": "string"
                }
            }
        },
        "vo.TopicVO": {
            "type": "object",
            "properties": {
                "article": {
                    "description": "文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.ArticleAccessTimesVO"
                    }
                },
                "title": {
                    "description": "专题名",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "生产：https://product.com 测试：http://test.com:9090 开发：http://localhost:9090",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "api",
	Description: "鹏sir笔记接口",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
