// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/article": {
            "get": {
                "description": "查询文章及相关信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "查询文章及相关信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "文章id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文章详情VO",
                        "schema": {
                            "$ref": "#/definitions/vo.ArticleEditVO"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            },
            "post": {
                "description": "保存文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "保存文章",
                "parameters": [
                    {
                        "description": "文章相关内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.ArticleParamsVO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文章id",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "删除文章",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "文章id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "http code = 200",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/admin/category/bindartcount": {
            "get": {
                "description": "查询绑定的文章条数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "查询绑定的文章条数",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "绑定文章条数",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/admin/category/bindtag": {
            "post": {
                "description": "绑定标签与文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "绑定标签与文章",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "专题id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "文章id",
                        "name": "aid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/admin/category/bindtopic": {
            "post": {
                "description": "绑定专题与文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "绑定专题与文章",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "专题id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "文章id",
                        "name": "aid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/admin/category/relations": {
            "delete": {
                "description": "通过文章id和分类id解除绑定关系",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "解除绑定关系",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "类别id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "文章id",
                        "name": "aid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/admin/category/tag": {
            "put": {
                "description": "更新标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "更新标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "标签id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "标签名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            },
            "post": {
                "description": "新增标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "新增标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "标签名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "文章id",
                        "name": "aid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "专题id",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "删除标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "标签id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/admin/category/tags": {
            "get": {
                "description": "查询标签列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "查询标签列表",
                "responses": {
                    "200": {
                        "description": "标签列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/datamodels.Category"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/admin/category/topic": {
            "put": {
                "description": "更新专题",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "更新专题",
                "parameters": [
                    {
                        "type": "string",
                        "description": "专题名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "专题id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            },
            "post": {
                "description": "新增专题",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "新增专题",
                "parameters": [
                    {
                        "type": "string",
                        "description": "专题名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "文章id",
                        "name": "aid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "专题id",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            },
            "delete": {
                "description": "通过专题id删除专题",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "删除专题",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "专题id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/admin/category/topics": {
            "get": {
                "description": "返回专题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客后台接口"
                ],
                "summary": "查询专题列表",
                "responses": {
                    "200": {
                        "description": "专题列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/datamodels.Category"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/article/content": {
            "get": {
                "description": "文章内容详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客前台接口"
                ],
                "summary": "文章内容详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文章标题",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "详情数据",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vo.ArticleContentVO"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/article/list": {
            "get": {
                "description": "分页接口通过page递增获取更多",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客前台接口"
                ],
                "summary": "首页文章列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页条数",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "列表数据",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vo.ArticleVO"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        },
        "/article/rank": {
            "get": {
                "description": "根据访问量排序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "博客前台接口"
                ],
                "summary": "文章访问TOP50",
                "responses": {
                    "200": {
                        "description": "列表数据",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vo.ArticleAccessTimesVO"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/errors.Errors"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "datamodels.Article": {
            "type": "object",
            "properties": {
                "ctime": {
                    "type": "string",
                    "readOnly": true
                },
                "id": {
                    "description": "文章表ID",
                    "type": "integer",
                    "readOnly": true,
                    "example": 1
                },
                "intro": {
                    "description": "简介",
                    "type": "string"
                },
                "intro_match": {
                    "description": "匹配简介",
                    "type": "string"
                },
                "is_del": {
                    "description": "0未删除；1已删除",
                    "type": "integer"
                },
                "is_encrypt": {
                    "description": "状态1明文；2密文",
                    "type": "integer"
                },
                "is_state": {
                    "description": "状态1私密；2公开",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "title_match": {
                    "description": "匹配标题",
                    "type": "string"
                },
                "uid": {
                    "description": "编辑者id",
                    "type": "integer"
                },
                "utime": {
                    "type": "string",
                    "readOnly": true
                }
            }
        },
        "datamodels.ArticleContent": {
            "type": "object",
            "properties": {
                "aid": {
                    "description": "文章id",
                    "type": "integer"
                },
                "data": {
                    "description": "文章内容",
                    "type": "string"
                }
            }
        },
        "datamodels.Category": {
            "type": "object",
            "properties": {
                "ctime": {
                    "type": "string",
                    "readOnly": true
                },
                "id": {
                    "description": "分类表ID",
                    "type": "integer",
                    "readOnly": true,
                    "example": 1
                },
                "info": {
                    "description": "简介",
                    "type": "string"
                },
                "name": {
                    "description": "专题/标签名称",
                    "type": "string"
                },
                "pid": {
                    "description": "父编号",
                    "type": "integer"
                },
                "type": {
                    "description": "类型1标签；2专题",
                    "type": "integer"
                },
                "utime": {
                    "type": "string",
                    "readOnly": true
                }
            }
        },
        "errors.Errors": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 4000000
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "vo.ArticleAccessTimesVO": {
            "type": "object",
            "properties": {
                "access_times": {
                    "description": "访问次数",
                    "type": "integer"
                },
                "title": {
                    "description": "文章标题",
                    "type": "string"
                }
            }
        },
        "vo.ArticleContentVO": {
            "type": "object",
            "properties": {
                "article": {
                    "description": "文章信息",
                    "$ref": "#/definitions/vo.ArticleVO"
                },
                "article_content": {
                    "description": "文章内容",
                    "$ref": "#/definitions/datamodels.ArticleContent"
                },
                "navigations": {
                    "description": "导航",
                    "$ref": "#/definitions/vo.NavigationVO"
                },
                "tags": {
                    "description": "标签文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.TagVO"
                    }
                },
                "topics": {
                    "description": "专题文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.TopicVO"
                    }
                }
            }
        },
        "vo.ArticleEditVO": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "文章内容",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "intro": {
                    "description": "文章简介",
                    "type": "string"
                },
                "is_encrypt": {
                    "description": "是否加密1明文2密文",
                    "type": "integer"
                },
                "is_state": {
                    "description": "状态1私有2公开",
                    "type": "integer"
                },
                "tags": {
                    "description": "标签ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "description": "文章标题",
                    "type": "string"
                },
                "topics": {
                    "description": "专题ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "vo.ArticleParamsVO": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "文章内容",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "intro": {
                    "description": "文章简介",
                    "type": "string"
                },
                "is_encrypt": {
                    "description": "是否加密1明文2密文",
                    "type": "integer"
                },
                "is_state": {
                    "description": "状态1私有2公开",
                    "type": "integer"
                },
                "title": {
                    "description": "文章标题",
                    "type": "string"
                }
            }
        },
        "vo.ArticleVO": {
            "type": "object",
            "properties": {
                "article": {
                    "$ref": "#/definitions/datamodels.Article"
                },
                "duration": {
                    "description": "持续时间",
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.NavigationVO": {
            "type": "object",
            "properties": {
                "next_title": {
                    "description": "下一文章title",
                    "type": "string"
                },
                "prev_title": {
                    "description": "上一文章title",
                    "type": "string"
                }
            }
        },
        "vo.TagVO": {
            "type": "object",
            "properties": {
                "article": {
                    "description": "文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.ArticleAccessTimesVO"
                    }
                },
                "title": {
                    "description": "专题名",
                    "type": "string"
                }
            }
        },
        "vo.TopicVO": {
            "type": "object",
            "properties": {
                "article": {
                    "description": "文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.ArticleAccessTimesVO"
                    }
                },
                "title": {
                    "description": "专题名",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8090",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "api",
	Description: "鹏sir笔记接口\\n环境信息：\\n生产：https://product.com\\n测试：http://test.com:8090\\n开发：http://localhost:8090",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
