definitions:
  datamodels.Article:
    properties:
      ctime:
        readOnly: true
        type: string
      id:
        description: 文章表ID
        example: 1
        readOnly: true
        type: integer
      intro:
        description: 简介
        type: string
      intro_match:
        description: 匹配简介
        type: string
      is_del:
        description: 0未删除；1已删除
        type: integer
      is_encrypt:
        description: 状态1明文；2密文
        type: integer
      is_state:
        description: 状态1私密；2公开
        type: integer
      title:
        description: 标题
        type: string
      title_match:
        description: 匹配标题
        type: string
      uid:
        description: 编辑者id
        type: integer
      utime:
        readOnly: true
        type: string
    type: object
  datamodels.ArticleContent:
    properties:
      aid:
        description: 文章id
        type: integer
      data:
        description: 文章内容
        type: string
    type: object
  datamodels.Category:
    properties:
      ctime:
        readOnly: true
        type: string
      id:
        description: 分类表ID
        example: 1
        readOnly: true
        type: integer
      info:
        description: 简介
        type: string
      name:
        description: 专题/标签名称
        type: string
      pid:
        description: 父编号
        type: integer
      type:
        description: 类型1标签；2专题
        type: integer
      utime:
        readOnly: true
        type: string
    type: object
  errors.Errors:
    properties:
      code:
        example: 4000000
        type: integer
      message:
        type: string
    type: object
  vo.ArticleAccessTimesVO:
    properties:
      access_times:
        description: 访问次数
        type: integer
      title:
        description: 文章标题
        type: string
    type: object
  vo.ArticleContentVO:
    properties:
      article:
        $ref: '#/definitions/vo.ArticleVO'
        description: 文章信息
      article_content:
        $ref: '#/definitions/datamodels.ArticleContent'
        description: 文章内容
      navigations:
        $ref: '#/definitions/vo.NavigationVO'
        description: 导航
      tags:
        description: 标签文章列表
        items:
          $ref: '#/definitions/vo.TagVO'
        type: array
      topics:
        description: 专题文章列表
        items:
          $ref: '#/definitions/vo.TopicVO'
        type: array
    type: object
  vo.ArticleEditVO:
    properties:
      content:
        description: 文章内容
        type: string
      id:
        type: integer
      intro:
        description: 文章简介
        type: string
      is_encrypt:
        description: 是否加密1明文2密文
        type: integer
      is_state:
        description: 状态1私有2公开
        type: integer
      tags:
        description: 标签ID列表
        items:
          type: integer
        type: array
      title:
        description: 文章标题
        type: string
      topics:
        description: 专题ID列表
        items:
          type: integer
        type: array
    type: object
  vo.ArticleListVO:
    properties:
      duration:
        description: 持续时间
        type: string
      id:
        type: integer
      title:
        description: 标题
        type: string
      title_match:
        description: 匹配的title
        type: string
    type: object
  vo.ArticleParamsVO:
    properties:
      content:
        description: 文章内容
        type: string
      id:
        type: integer
      intro:
        description: 文章简介
        type: string
      is_encrypt:
        description: 是否加密1明文2密文
        type: integer
      is_state:
        description: 状态1私有2公开
        type: integer
      title:
        description: 文章标题
        type: string
    type: object
  vo.ArticleVO:
    properties:
      article:
        $ref: '#/definitions/datamodels.Article'
      duration:
        description: 持续时间
        type: string
      tags:
        items:
          type: string
        type: array
      topics:
        items:
          type: string
        type: array
    type: object
  vo.NavigationVO:
    properties:
      next_title:
        description: 下一文章title
        type: string
      prev_title:
        description: 上一文章title
        type: string
    type: object
  vo.TagVO:
    properties:
      article:
        description: 文章列表
        items:
          $ref: '#/definitions/vo.ArticleAccessTimesVO'
        type: array
      title:
        description: 专题名
        type: string
    type: object
  vo.TopicVO:
    properties:
      article:
        description: 文章列表
        items:
          $ref: '#/definitions/vo.ArticleAccessTimesVO'
        type: array
      title:
        description: 专题名
        type: string
    type: object
host: localhost:8090
info:
  contact: {}
  description: 鹏sir笔记接口\n环境信息：\n生产：https://product.com\n测试：http://test.com:8090\n开发：http://localhost:8090
  title: api
  version: "1.0"
paths:
  /admin/article:
    delete:
      consumes:
      - application/json
      description: 删除文章
      parameters:
      - description: 文章id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 删除文章
      tags:
      - 博客后台接口
    get:
      consumes:
      - application/json
      description: 查询文章及相关信息
      parameters:
      - description: 文章id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 文章详情VO
          schema:
            $ref: '#/definitions/vo.ArticleEditVO'
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 查询文章及相关信息
      tags:
      - 博客后台接口
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 保存文章
      parameters:
      - description: 文章相关内容
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/vo.ArticleParamsVO'
      produces:
      - text/plain
      responses:
        "200":
          description: 文章id
          schema:
            type: integer
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 保存文章
      tags:
      - 博客后台接口
  /admin/articles:
    get:
      consumes:
      - application/json
      description: 查询文章列表
      parameters:
      - description: 关键词
        in: query
        name: keyword
        type: string
      - description: 页码
        in: query
        name: page
        required: true
        type: integer
      - description: 每页条数
        in: query
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 文章列表VO
          schema:
            $ref: '#/definitions/vo.ArticleListVO'
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 查询文章列表
      tags:
      - 博客后台接口
  /admin/category/bindartcount:
    get:
      consumes:
      - application/json
      description: 查询绑定的文章条数
      parameters:
      - description: 分类id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: 绑定文章条数
          schema:
            type: integer
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 查询绑定的文章条数
      tags:
      - 博客后台接口
  /admin/category/bindtag:
    post:
      consumes:
      - application/json
      description: 绑定标签与文章
      parameters:
      - description: 专题id
        in: query
        name: id
        required: true
        type: integer
      - description: 文章id
        in: query
        name: aid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 绑定标签与文章
      tags:
      - 博客后台接口
  /admin/category/bindtopic:
    post:
      consumes:
      - application/json
      description: 绑定专题与文章
      parameters:
      - description: 专题id
        in: query
        name: id
        required: true
        type: integer
      - description: 文章id
        in: query
        name: aid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 绑定专题与文章
      tags:
      - 博客后台接口
  /admin/category/relations:
    delete:
      consumes:
      - application/json
      description: 通过文章id和分类id解除绑定关系
      parameters:
      - description: 类别id
        in: query
        name: id
        required: true
        type: integer
      - description: 文章id
        in: query
        name: aid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 解除绑定关系
      tags:
      - 博客后台接口
  /admin/category/tag:
    delete:
      consumes:
      - application/json
      description: 删除标签
      parameters:
      - description: 标签id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 删除标签
      tags:
      - 博客后台接口
    post:
      consumes:
      - application/json
      description: 新增标签
      parameters:
      - description: 标签名称
        in: query
        name: name
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: 专题id
          schema:
            type: integer
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 新增标签
      tags:
      - 博客后台接口
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 更新标签
      parameters:
      - description: 标签id
        in: formData
        name: id
        required: true
        type: integer
      - description: 标签名称
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 更新标签
      tags:
      - 博客后台接口
  /admin/category/tags:
    get:
      consumes:
      - application/json
      description: 查询标签列表
      produces:
      - application/json
      responses:
        "200":
          description: 标签列表
          schema:
            items:
              $ref: '#/definitions/datamodels.Category'
            type: array
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 查询标签列表
      tags:
      - 博客后台接口
  /admin/category/topic:
    delete:
      consumes:
      - application/json
      description: 通过专题id删除专题
      parameters:
      - description: 专题id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 删除专题
      tags:
      - 博客后台接口
    post:
      consumes:
      - application/json
      description: 新增专题
      parameters:
      - description: 专题名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 专题id
          schema:
            type: integer
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 新增专题
      tags:
      - 博客后台接口
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 更新专题
      parameters:
      - description: 专题id
        in: formData
        name: id
        required: true
        type: integer
      - description: 专题名称
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 更新专题
      tags:
      - 博客后台接口
  /admin/category/topics:
    get:
      consumes:
      - application/json
      description: 返回专题列表
      produces:
      - application/json
      responses:
        "200":
          description: 专题列表
          schema:
            items:
              $ref: '#/definitions/datamodels.Category'
            type: array
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 查询专题列表
      tags:
      - 博客后台接口
  /article/content:
    get:
      consumes:
      - application/json
      description: 文章内容详情
      parameters:
      - description: 文章标题
        in: query
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 详情数据
          schema:
            items:
              $ref: '#/definitions/vo.ArticleContentVO'
            type: array
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 文章内容详情
      tags:
      - 博客前台接口
  /article/list:
    get:
      consumes:
      - application/json
      description: 分页接口通过page递增获取更多
      parameters:
      - description: 关键词
        in: query
        name: keyword
        type: string
      - description: 页码
        in: query
        name: page
        required: true
        type: integer
      - description: 每页条数
        in: query
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 列表数据
          schema:
            items:
              $ref: '#/definitions/vo.ArticleVO'
            type: array
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 首页文章列表
      tags:
      - 博客前台接口
  /article/rank:
    get:
      consumes:
      - application/json
      description: 根据访问量排序
      produces:
      - application/json
      responses:
        "200":
          description: 列表数据
          schema:
            items:
              $ref: '#/definitions/vo.ArticleAccessTimesVO'
            type: array
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 文章访问TOP50
      tags:
      - 博客前台接口
swagger: "2.0"
